Console.BackgroundColor = ConsoleColor.Blue;
Console.Clear();
int A = 440;
int B = 494;
int C = 262;
int D = 294; 
int E = 330; 
int F = 349;
int G = 392;
int HA = 880;
int HB = 988;
int HC = 523;
int HD = 587;
int HE = 659;
int HF = 699;
int HG = 784;
int wholeNote = 3500;
int hn = wholeNote/2;
int qn = wholeNote/4;
int DotHN = wholeNote * (3/4) +1;
Console.BackgroundColor = ConsoleColor.White;
Console.Clear();
Console.Beep(HG,DotHN);
Console.BackgroundColor = ConsoleColor.DarkGray;
Console.Clear();
Console.Beep(HE,wholeNote);
Console.BackgroundColor = ConsoleColor.Green;
Console.Clear();
Console.Beep(HD,qn);
Console.BackgroundColor = ConsoleColor.DarkGray;
Console.Clear();
Console.Beep(HE,qn);
Console.BackgroundColor = ConsoleColor.Green;
Console.Clear();
Console.Beep(HD,wholeNote);
Console.BackgroundColor = ConsoleColor.Blue;
Console.Clear();
Console.Beep(HC,qn);
Console.BackgroundColor = ConsoleColor.Green;
Console.Clear();
Console.Beep(HD,qn);
Console.BackgroundColor = ConsoleColor.Blue;
Console.Clear();
Console.Beep(HC,qn);
Console.BackgroundColor = ConsoleColor.DarkGray;
Console.Clear();
Console.Beep(HE,qn);
Console.BackgroundColor = ConsoleColor.Blue;
Console.Clear();
Console.Beep(HC,hn);
Console.BackgroundColor = ConsoleColor.Magenta;
Console.Clear();
Console.Beep(B,qn);
Console.BackgroundColor = ConsoleColor.Blue;
Console.Clear();
Console.Beep(HC,qn);
Console.BackgroundColor = ConsoleColor.Magenta;
Console.Clear();
Console.Beep(B,DotHN);
//Console.BackgroundColor = ConsoleColor.Black;
//Console.Clear();
//Console.Beep(2,qn);
Console.BackgroundColor = ConsoleColor.Cyan;
Console.Clear();
Console.Beep(A,qn);
Console.BackgroundColor = ConsoleColor.Magenta;
Console.Clear();
Console.Beep(B,qn);
Console.BackgroundColor = ConsoleColor.Cyan;
Console.Clear();
Console.Beep(A,qn);
Console.BackgroundColor = ConsoleColor.Green;
Console.Clear();
Console.Beep(HD,qn);
Console.BackgroundColor = ConsoleColor.Cyan;
Console.Clear();
Console.Beep(A,qn);
Console.BackgroundColor = ConsoleColor.Blue;
Console.Clear();
Console.Beep(G,qn);
Console.BackgroundColor = ConsoleColor.Cyan;
Console.Clear();
Console.Beep(A,qn);
Console.BackgroundColor = ConsoleColor.Blue;
Console.Clear();
Console.Beep(G,hn);
Console.BackgroundColor = ConsoleColor.DarkGreen;
Console.Clear();
Console.Beep(F,qn);
Console.BackgroundColor = ConsoleColor.Blue;
Console.Clear();
Console.Beep(G,qn);
Console.BackgroundColor = ConsoleColor.DarkGreen;
Console.Clear();
Console.Beep(F,DotHN);
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Clear();
Console.Beep(E,wholeNote);
Console.BackgroundColor = ConsoleColor.Red;
Console.Clear();
Console.Beep(E,qn);
Console.BackgroundColor = ConsoleColor.DarkGreen;
Console.Clear();
Console.Beep(F,qn);
Console.BackgroundColor = ConsoleColor.Red;
Console.Clear();
Console.Beep(E,qn);
Console.BackgroundColor = ConsoleColor.Cyan;
Console.Clear();
Console.Beep(A,qn);
Console.BackgroundColor = ConsoleColor.Red;
Console.Clear();
Console.Beep(E,qn);
Console.BackgroundColor = ConsoleColor.Blue;
Console.Clear();
Console.Beep(D,qn);
Console.BackgroundColor = ConsoleColor.Red;
Console.Clear();
Console.Beep(E,qn);
Console.BackgroundColor = ConsoleColor.Green;
Console.Clear();
Console.Beep(D,hn);
Console.BackgroundColor = ConsoleColor.DarkGray;
Console.Clear();
Console.Beep(C,qn);
Console.BackgroundColor = ConsoleColor.Green;
Console.Clear();
Console.Beep(D,qn);
Console.BackgroundColor = ConsoleColor.DarkGray;
Console.Clear();
Console.Beep(C,DotHN);
Console.BackgroundColor = ConsoleColor.Black;
Console.Clear();
Console.Beep(247,wholeNote);
